/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import enums.ColorTheme;
import aps.Colors;
import enums.PageEnum;
import aps.Pages;
import components.Alert;
import components.FieldInterface;
import controllers.UserController;
import exceptions.ServerErrorException;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import validations.Validation;

/**
 *
 * @author guilh
 */
public class LoginForm extends javax.swing.JFrame {

    private final UserController loginController;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        this.loginController = new UserController();
        initComponents();
        
        emailField.setValidations("required|email");
        passwordField.setValidations("required");
    }

    public LoginForm(String email, String password) {
        this.loginController = new UserController();
        initComponents();

        emailField.setText(email);
        passwordField.setText(password);
    }

    private void changeTheme() {
        Colors.setTheme(Colors.isDarkTheme() ? ColorTheme.LIGHT : ColorTheme.DARK);

        String password = new String(passwordField.getPassword());

        LoginForm loginForm = new LoginForm(emailField.getText(), password);

        String imageName = Colors.isDarkTheme() ? "sunny" : "night";
        String iconThemePath = "/assets/weather-" + imageName + ".png";

        loginForm.buttonTheme.setIcon(new ImageIcon(getClass().getResource(iconThemePath)));

        Pages.setPage(PageEnum.LOGIN, loginForm);
        Pages.setPage(PageEnum.REGISTER, new RegisterForm());

        Pages.redirect(PageEnum.LOGIN, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameContent = new javax.swing.JPanel();
        FormContent = new javax.swing.JPanel();
        InputContent1 = new javax.swing.JPanel();
        EmailLabel1 = new javax.swing.JLabel();
        emailField = new components.TextFieldComponent();
        InputContent = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        passwordField = new components.PasswordFieldComponent();
        ButtonContent = new javax.swing.JPanel();
        buttonComponent1 = new components.ButtonComponent();
        LinkContent = new javax.swing.JPanel();
        linkText = new javax.swing.JLabel();
        buttonLinkComponent1 = new components.ButtonLinkComponent();
        Logo = new javax.swing.JLabel();
        buttonTheme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        FrameContent.setBackground(Colors.getLight());
        FrameContent.setPreferredSize(new java.awt.Dimension(500, 500));
        FrameContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FormContent.setBackground(Colors.getLight());
        FormContent.setLayout(new java.awt.GridLayout(4, 1));

        InputContent1.setBackground(Colors.getLight());
        InputContent1.setLayout(new java.awt.GridLayout(2, 0, 0, 4));

        EmailLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        EmailLabel1.setForeground(Colors.getPrimary());
        EmailLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailLabel1.setText("Email:");
        EmailLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        InputContent1.add(EmailLabel1);

        emailField.setPreferredSize(new java.awt.Dimension(64, 40));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        InputContent1.add(emailField);

        FormContent.add(InputContent1);

        InputContent.setBackground(Colors.getLight());
        InputContent.setLayout(new java.awt.GridLayout(2, 0, 0, 4));

        EmailLabel.setBackground(new java.awt.Color(75, 101, 132));
        EmailLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        EmailLabel.setForeground(Colors.getPrimary());
        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailLabel.setText("Senha:");
        EmailLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        InputContent.add(EmailLabel);
        InputContent.add(passwordField);

        FormContent.add(InputContent);

        ButtonContent.setBackground(Colors.getLight());
        ButtonContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonComponent1.setText("Entrar");
        buttonComponent1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        buttonComponent1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonComponent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonComponent1MouseClicked(evt);
            }
        });
        ButtonContent.add(buttonComponent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 380, 40));

        FormContent.add(ButtonContent);

        LinkContent.setBackground(Colors.getLight());
        LinkContent.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 26);
        flowLayout1.setAlignOnBaseline(true);
        LinkContent.setLayout(flowLayout1);

        linkText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        linkText.setForeground(Colors.getText());
        linkText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkText.setText("Não possui um cadastro?");
        LinkContent.add(linkText);

        buttonLinkComponent1.setText("Clique Aqui");
        buttonLinkComponent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLinkComponent1MouseClicked(evt);
            }
        });
        LinkContent.add(buttonLinkComponent1);

        FormContent.add(LinkContent);

        FrameContent.add(FormContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 90, 382, -1));

        Logo.setFont(new java.awt.Font("Impact", 2, 22)); // NOI18N
        Logo.setForeground(Colors.getPrimary());
        Logo.setText("Socket.messager");
        FrameContent.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 32, 290, -1));

        buttonTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/weather-night.png"))); // NOI18N
        buttonTheme.setBorder(null);
        buttonTheme.setBorderPainted(false);
        buttonTheme.setContentAreaFilled(false);
        buttonTheme.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonThemeMouseClicked(evt);
            }
        });
        buttonTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemeActionPerformed(evt);
            }
        });
        FrameContent.add(buttonTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(516, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLinkComponent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLinkComponent1MouseClicked
        Pages.setPage(PageEnum.REGISTER, new RegisterForm());
        Pages.redirect(PageEnum.REGISTER, this);
    }//GEN-LAST:event_buttonLinkComponent1MouseClicked

    private void buttonComponent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonComponent1MouseClicked
        FieldInterface[] fields = {emailField, passwordField};

        if (Validation.validate(fields)) {
            try {
                String email = emailField.getText();
                String password = new String(passwordField.getPassword());

                loginController.authenticate(email, password);

                Pages.redirect(PageEnum.CHAT, this);
            } catch (SQLException ex) {
                Alert.error("Usuário inválido", "Email e/ou senha inválidos");
            } catch (IOException ex) {
                try {
                    throw new ServerErrorException(ex.getMessage());
                } catch (ServerErrorException ex1) {
                }
            }
        }
    }//GEN-LAST:event_buttonComponent1MouseClicked

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void buttonThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonThemeActionPerformed

    private void buttonThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonThemeMouseClicked
        changeTheme();
    }//GEN-LAST:event_buttonThemeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonContent;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel EmailLabel1;
    private javax.swing.JPanel FormContent;
    private javax.swing.JPanel FrameContent;
    private javax.swing.JPanel InputContent;
    private javax.swing.JPanel InputContent1;
    private javax.swing.JPanel LinkContent;
    private javax.swing.JLabel Logo;
    private components.ButtonComponent buttonComponent1;
    private components.ButtonLinkComponent buttonLinkComponent1;
    private javax.swing.JButton buttonTheme;
    private components.TextFieldComponent emailField;
    private javax.swing.JLabel linkText;
    private components.PasswordFieldComponent passwordField;
    // End of variables declaration//GEN-END:variables
}
