/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import aps.Colors;
import enums.PageEnum;
import aps.Pages;
import components.Alert;
import components.FieldInterface;
import controllers.UserController;
import validations.Validation;

/**
 *
 * @author guilh
 */
public class RegisterForm extends javax.swing.JFrame {

    private final UserController loginController;

    /**
     * Creates new form LoginForm
     */
    public RegisterForm() {
        this.loginController = new UserController();
        initComponents();
        
        nameField.setValidations("required");
        emailField.setValidations("required|email");
        passwordField.setValidations("required|min:8");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FormContent = new javax.swing.JPanel();
        InputContent2 = new javax.swing.JPanel();
        EmailLabel2 = new javax.swing.JLabel();
        nameField = new components.TextFieldComponent();
        InputContent1 = new javax.swing.JPanel();
        EmailLabel1 = new javax.swing.JLabel();
        emailField = new components.TextFieldComponent();
        InputContent = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        passwordField = new components.PasswordFieldComponent();
        ButtonContent = new javax.swing.JPanel();
        buttonComponent1 = new components.ButtonComponent();
        LinkContent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonLinkComponent1 = new components.ButtonLinkComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        FrameContent.setBackground(Colors.getLight());
        FrameContent.setPreferredSize(new java.awt.Dimension(500, 500));
        FrameContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 2, 22)); // NOI18N
        jLabel2.setForeground(Colors.getPrimary());
        jLabel2.setText("Socket.messager");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FrameContent.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 32, 290, -1));

        FormContent.setBackground(Colors.getLight());
        FormContent.setLayout(new java.awt.GridLayout(5, 1));

        InputContent2.setBackground(Colors.getLight());
        InputContent2.setLayout(new java.awt.GridLayout(2, 0, 0, 4));

        EmailLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        EmailLabel2.setForeground(Colors.getPrimary());
        EmailLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailLabel2.setText("Nome:");
        EmailLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        InputContent2.add(EmailLabel2);

        nameField.setPreferredSize(new java.awt.Dimension(64, 40));
        InputContent2.add(nameField);

        FormContent.add(InputContent2);

        InputContent1.setBackground(Colors.getLight());
        InputContent1.setLayout(new java.awt.GridLayout(2, 0, 0, 4));

        EmailLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        EmailLabel1.setForeground(Colors.getPrimary());
        EmailLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailLabel1.setText("Email:");
        EmailLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        InputContent1.add(EmailLabel1);

        emailField.setPreferredSize(new java.awt.Dimension(64, 40));
        InputContent1.add(emailField);

        FormContent.add(InputContent1);

        InputContent.setBackground(Colors.getLight());
        InputContent.setLayout(new java.awt.GridLayout(2, 0, 0, 4));

        EmailLabel.setBackground(new java.awt.Color(75, 101, 132));
        EmailLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        EmailLabel.setForeground(Colors.getPrimary());
        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EmailLabel.setText("Senha:");
        EmailLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        InputContent.add(EmailLabel);
        InputContent.add(passwordField);

        FormContent.add(InputContent);

        ButtonContent.setBackground(Colors.getLight());
        ButtonContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonComponent1.setText("Registrar");
        buttonComponent1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        buttonComponent1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonComponent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonComponent1MouseClicked(evt);
            }
        });
        buttonComponent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonComponent1ActionPerformed(evt);
            }
        });
        ButtonContent.add(buttonComponent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 380, 40));

        FormContent.add(ButtonContent);

        LinkContent.setBackground(Colors.getLight());
        LinkContent.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 26);
        flowLayout1.setAlignOnBaseline(true);
        LinkContent.setLayout(flowLayout1);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(Colors.getText());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Já possui um cadastro?");
        LinkContent.add(jLabel1);

        buttonLinkComponent1.setText("Entrar");
        buttonLinkComponent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLinkComponent1MouseClicked(evt);
            }
        });
        buttonLinkComponent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLinkComponent1ActionPerformed(evt);
            }
        });
        LinkContent.add(buttonLinkComponent1);

        FormContent.add(LinkContent);

        FrameContent.add(FormContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 56, 382, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(516, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonComponent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComponent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonComponent1ActionPerformed

    private void buttonLinkComponent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLinkComponent1MouseClicked
        Pages.redirect(PageEnum.LOGIN, this);
    }//GEN-LAST:event_buttonLinkComponent1MouseClicked

    private void buttonLinkComponent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLinkComponent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLinkComponent1ActionPerformed

    private void buttonComponent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonComponent1MouseClicked
        FieldInterface[] fields = {nameField, emailField, passwordField};

        if (Validation.validate(fields)) {
            String name = nameField.getText();
            String email = emailField.getText();
            String password = new String(passwordField.getPassword());

            loginController.register(name, email, password);

            Alert.success("Usuário adicionado", "usuário adicionado com sucesso!");
            Pages.redirect(PageEnum.LOGIN, this);
        }

    }//GEN-LAST:event_buttonComponent1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonContent;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel EmailLabel1;
    private javax.swing.JLabel EmailLabel2;
    private javax.swing.JPanel FormContent;
    private javax.swing.JPanel FrameContent;
    private javax.swing.JPanel InputContent;
    private javax.swing.JPanel InputContent1;
    private javax.swing.JPanel InputContent2;
    private javax.swing.JPanel LinkContent;
    private components.ButtonComponent buttonComponent1;
    private components.ButtonLinkComponent buttonLinkComponent1;
    private components.TextFieldComponent emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private components.TextFieldComponent nameField;
    private components.PasswordFieldComponent passwordField;
    // End of variables declaration//GEN-END:variables
}
